# Generated by Django 4.1.2 on 2022-10-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C19app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(default='Anonymous', error_messages={'max_length': 'Name must not pass 200 characters'}, help_text='Name of Demiz visitor', max_length=200, verbose_name="Visitor's Name"),
        ),
    ]
