# Generated by Django 4.1.2 on 2022-10-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C19app', '0002_alter_comments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.TimeField(auto_now=True),
        ),
    ]
