# Generated by Django 4.1.2 on 2022-10-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C19app', '0005_alter_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
