# Generated by Django 4.1.2 on 2022-10-27 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C19app', '0007_alter_comments_date_alter_comments_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 22, 50, 14)),
        ),
    ]
