# Generated by Django 4.1.2 on 2022-10-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('C19app', '0010_remove_comments_time_alter_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='You did a great job Demiz', help_text='Enter comments here'),
        ),
    ]
